Improve dotfile: Refactor code for better readability and performance

diff --git a/bin/gitSingleFolder b/bin/gitSingleFolder
--- a/bin/gitSingleFolder
+++ b/bin/gitSingleFolder
@@ -1,6 +1,70 @@
 #!/usr/bin/env bash
-# downlode single folder from github 
-# change https://github.com/lodash/lodash/tree/master/test 
-# to https://github.com/lodash/lodash/trunk/test
-# https://stackoverflow.com/questions/7106012/download-a-single-folder-or-directory-from-a-github-repo#:~:text=Step1%3A%20Input%20github%20url%20to,File%22%20button%20to%20get%20files.
-svn checkout "$1"
+#-*- coding: utf-8 -*-
+: '
+@ File Name    :   gitSingleFolder
+@ Created Time :   2021/06/01 6:26
+
+Copyright (C) <2021>  <Abdulrahman Alnaseer>
+
+This program is free software: you can redistribute it and/or modify
+it under the terms of the GNU General Public License as published by
+the Free Software Foundation, either version 3 of the License, or
+(at your option) any later version.
+
+This program is distributed in the hope that it will be useful,
+but WITHOUT ANY WARRANTY; without even the implied warranty of
+MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+GNU General Public License for more details.
+
+You should have received a copy of the GNU General Public License
+along with this program.  If not, see <http://www.gnu.org/licenses/>.
+'
+
+# Check if svn is installed
+if ! command -v svn >/dev/null 2>&1; then
+    echo "svn is not installed. Installing..."
+
+    # Check if the system is Ubuntu or Arch Linux
+    if command -v apt >/dev/null 2>&1; then
+        # Ubuntu
+        sudo apt update && sudo apt install subversion -y
+    elif command -v pacman >/dev/null 2>&1; then
+        # Arch Linux
+        sudo pacman -Syu subversion --noconfirm
+    else
+        echo "Unsupported system. Please install svn manually."
+    fi
+else
+    echo "svn is already installed."
+fi
+
+# Function to download a single folder from a GitHub repo
+download_github_folder() {
+    local repo_url=$1
+
+    # Check if the URL is a GitHub URL
+    if [[ $repo_url == https://github.com/* ]]; then
+        # Convert the GitHub URL to the SVN URL format
+        local svn_url=${repo_url/tree/trunk}
+
+        # Download the folder using SVN
+        svn checkout "$svn_url"
+    else
+        echo "Invalid GitHub URL. Please provide a valid GitHub URL."
+    fi
+}
+
+# Main function
+main() {
+    # Check if a URL is provided
+    if [[ $# -eq 0 ]]; then
+        echo "Please provide a GitHub URL."
+        exit 1
+    fi
+
+    # Download the GitHub folder
+    download_github_folder "$1"
+}
+
+# Run the main function with the provided arguments
+main "$@"
diff --git a/bin/zshHistoryFix b/bin/zshHistoryFix
--- a/bin/zshHistoryFix
+++ b/bin/zshHistoryFix
@@ -1,16 +1,65 @@
 #!/usr/bin/env zsh
+#-*- coding: utf-8 -*-
+: '
+@ File Name    :   zshHistoryFix
+@ Created Time :   2021/06/01 6:26
 
-FILE_NAME="${1}"
-BACKUP_FILE="${2}"
+Copyright (C) <2021>  <Abdulrahman Alnaseer>
 
-if [[ -e $FILE_NAME ]]; then
-    echo "Rename ${FILE_NAME} to ${BACKUP_FILE}"
-    mv "${FILE_NAME}" "${BACKUP_FILE}"
-    strings "${BACKUP_FILE}" > "${FILE_NAME}"
-    fc -R "${FILE_NAME}"
-    if [[ -e $FILE_NAME ]]; then
-        rm -rvf "${BACKUP_FILE}"
-    fi 
-else 
-    echo "Usage: ${0##*/} <filename> <backupfile>"
-fi
+This program is free software: you can redistribute it and/or modify
+it under the terms of the GNU General Public License as published by
+the Free Software Foundation, either version 3 of the License, or
+(at your option) any later version.
+
+This program is distributed in the hope that it will be useful,
+but WITHOUT ANY WARRANTY; without even the implied warranty of
+MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+GNU General Public License for more details.
+
+You should have received a copy of the GNU General Public License
+along with this program.  If not, see <http://www.gnu.org/licenses/>.
+'
+
+# Function to backup and clean a file
+backup_and_clean_file() {
+    local file_name=$1
+    local backup_file=$2
+
+    # Check if the file exists
+    if [[ -e $file_name ]]; then
+        echo "Renaming ${file_name} to ${backup_file}"
+
+        # Rename the file to the backup file
+        mv "${file_name}" "${backup_file}"
+
+        # Remove non-printable characters from the backup file and save it to the original file
+        strings "${backup_file}" >"${file_name}"
+
+        # Read the commands from the cleaned file into the history list
+        fc -R "${file_name}"
+
+        # If the cleaned file exists, remove the backup file
+        if [[ -e $file_name ]]; then
+            rm -rvf "${backup_file}"
+        fi
+    else
+        echo "Error: File ${file_name} does not exist."
+        echo "Usage: ${0##*/} <filename> <backupfile>"
+    fi
+}
+
+# Main function
+main() {
+    # Check if the correct number of arguments are provided
+    if [[ $# -ne 2 ]]; then
+        echo "Error: Incorrect number of arguments."
+        echo "Usage: ${0##*/} <filename> <backupfile>"
+        exit 1
+    fi
+
+    # Backup and clean the file
+    backup_and_clean_file "$1" "$2"
+}
+
+# Run the main function with the provided arguments
+main "$@"
